server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/otpdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: verysecretkeyforjwtmustbe32chars
  expiration: 3600000
